name: Build Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # or: 'beta' or 'master'
    - run: flutter --version
    - run: flutter pub global activate peanut
    - run: flutter pub get
    - run: |
        git config --global user.name syhien
        git config --global user.email syhien@outlook.at
    - run: flutter pub global run peanut -b production
    - run: |
        git checkout -f production
        git push --set-upstream --force origin production
