name: Build Pages
on:
  push
  workflow_dispatch:

jobs:
  build:
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # or: 'beta' or 'master'
    - run: flutter --version
    - run: flutter pub global activate peanut
    - run: flutter pub get
    - run: flutter pub global run peanut -b production